### ISSUE TITLE
Cannot stop reactor.run() gracefully

### ISSUE THREAD

**Issue by al2389** [derekstavis/python-sysfs-gpio#22]
Test code:

```
#!/usr/bin/python
import sys
import signal
from twisted.internet import reactor
from sysfs.gpio import Controller, OUTPUT, INPUT, RISING

port = 6

''' This works '''
def signal_handler(signal, frame):
	Controller.dealloc_pin(port)
 	print('You pressed Ctrl+C!')
 	reactor.stop()
 	
 ''' This will cause an error '''
def pin_changed(number, state):
	Controller.dealloc_pin(port)
	print("Pin '%d' changed to %d state" % (number, state))
	reactor.stop()
 
signal.signal(signal.SIGINT, signal_handler)
 
Controller.available_pins = [port]
pin = Controller.alloc_pin(port, INPUT, pin_changed, RISING)
pin.read()  # Reads pin logic level

reactor.run()
```

Result:

```
root@orangepipc2:~# python /tmp/test_sysfs-gpio.py
SysfsGPIO: alloc_pin(6, in, <function pin_changed at 0xffffba0b82a8>, rising, 0)
^CSysfsGPIO: dealloc_pin(6)
You pressed Ctrl+C!
root@orangepipc2:~# python /tmp/test_sysfs-gpio.py
SysfsGPIO: alloc_pin(6, in, <function pin_changed at 0xffffab9652a8>, rising, 0)
SysfsGPIO: dealloc_pin(6)
Pin '6' changed to 1 state
Unhandled Error
Traceback (most recent call last):
  File "/tmp/test_sysfs-gpio.py", line 27, in <module>
    reactor.run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 851, in runUntilCurrent
    f(*a, **kw)
  File "build/bdist.linux-aarch64/egg/sysfs/gpio.py", line 400, in _poll_queue_event

exceptions.RuntimeError: dictionary changed size during iteration

root@orangepipc2:~#
```

Did I miss anything ?

**Comment by al2389** [comment]
```
def pin_changed(number, state):
    # Controller.dealloc_pin(port) -- remove this line
    print("Pin '%d' changed to %d state" % (number, state))
    reactor.stop()
```
reactor.stop() directly **without** Controller.dealloc_pin(port) or Controller.stop() is Okay, no more error.
